FROM node:16.13.0-alpine as build
WORKDIR /app
COPY ["package.json", "package-lock.json", "./"]
COPY . .
RUN npm install --silent && npm run build

FROM nginx:alpine
COPY --from=build /app/dist/frontend /usr/share/nginx/html
COPY ./gcp/default.conf.template /etc/nginx/conf.d/default.conf.template
CMD /bin/sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'
