version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=d4REn0LdCH4B
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks: 
      - db  
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    ports:
      - 15432:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    networks: 
      - db

  jccapi:
    image: jcc_api:1.0
    depends_on:
      - postgres
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DATABASE_URL=server=postgres;port=5432;userid=postgres;database=my-db;password=d4REn0LdCH4B;
    networks: 
      - backend

  frontend:
    image: jcc_frontend:1.0
    ports:
      - 80:8080
    depends_on:
      - jccapi
    networks: 
      - backend

volumes:
  postgres-data:

networks:
  db:
  backend:
