// <auto-generated />
using System;
using JccApi.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace JccApi.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20211120192220_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("JccApi.Entities.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnName("age")
                        .HasColumnType("text");

                    b.Property<string>("ClothesSize")
                        .IsRequired()
                        .HasColumnName("clothes_size")
                        .HasColumnType("text");

                    b.Property<string>("FamilyAcronym")
                        .IsRequired()
                        .HasColumnName("family_acronym")
                        .HasColumnType("text");

                    b.Property<string>("FamilyAddress")
                        .IsRequired()
                        .HasColumnName("family_address")
                        .HasColumnType("text");

                    b.Property<string>("FamilyPhone")
                        .IsRequired()
                        .HasColumnName("family_phone")
                        .HasColumnType("text");

                    b.Property<string>("LegalResponsible")
                        .IsRequired()
                        .HasColumnName("legal_responsible")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("ShoesSize")
                        .IsRequired()
                        .HasColumnName("shoes_size")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("children");
                });

            modelBuilder.Entity("JccApi.Entities.GodParent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsClothesSelected")
                        .HasColumnName("is_clothes_selected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGiftSelected")
                        .HasColumnName("is_gift_selected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShoesSelected")
                        .HasColumnName("is_shoes_selected")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnName("phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("god_parents");
                });

            modelBuilder.Entity("JccApi.Entities.GodParent", b =>
                {
                    b.HasOne("JccApi.Entities.Child", "Child")
                        .WithMany("GodParents")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
